# Generated by Django 4.2.1 on 2023-06-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField(verbose_name='task due date')),
                ('completed', models.BooleanField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.URLField(max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
            preserve_default=False,
        ),
    ]
