# Generated by Django 4.2.1 on 2023-06-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_video_journal_project_journals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='task',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
    ]
