# Generated by Django 4.2.1 on 2023-06-07 21:21

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_journal_task_remove_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.CharField(default='very important task', verbose_name=main_app.models.Task),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.URLField(default='www.github.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='very important project', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-12-30', verbose_name='task due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='detailed description', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='important task', max_length=100),
        ),
    ]
