# Generated by Django 4.2.1 on 2023-06-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_project_tasks_alter_project_links_alter_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
    ]
