# Generated by Django 4.2.1 on 2023-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.URLField(default='www.github.com'),
        ),
    ]
