# Generated by Django 4.2.1 on 2023-06-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='journals',
        ),
        migrations.RemoveField(
            model_name='project',
            name='youtube_tutorials',
        ),
        migrations.AddField(
            model_name='journal',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ForeignKey(default='very important task', on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
        ),
    ]
