# Generated by Django 4.2.1 on 2023-06-09 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_rename_links_project_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='task_name',
            new_name='task',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
