# Generated by Django 4.2.1 on 2023-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_journal_options_rename_name_video_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_title',
            field=models.CharField(default='great channel', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='great description', max_length=200),
        ),
    ]
