# Generated by Django 4.2.1 on 2023-06-11 19:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_video_channel_title_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='youtube.com'),
        ),
    ]
