# Generated by Django 4.2.1 on 2023-06-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_task_project_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='entries',
            field=models.ManyToManyField(to='main_app.journal'),
        ),
    ]
