# Generated by Django 4.2.1 on 2023-06-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_task_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
